### ISSUE TITLE
0.4.0 fails to build in Ubuntu 16.10 (with GTK 3.20)

### ISSUE THREAD

**Issue by hotice** [vinszent/gnome-twitch#248]
I'm trying to build the latest Gnome Twitch 0.4.0 in my PPA but it fails to build for Ubuntu 16.10 (with GTK 3.20), with the following error:
```
./build/../src/gt-chat.c:443: undefined reference to `gtk_show_uri_on_window'
src/gnome-twitch@exe/utils.c.o: In function `utils_mouse_clicked_link_cb':
./build/../src/utils.c:195: undefined reference to `gtk_show_uri_on_window'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```
You can find a complete build log here: https://launchpadlibrarian.net/314209047/buildlog_ubuntu-yakkety-amd64.gnome-twitch_0.4.0-1~webupd8~yakkety2_BUILDING.txt.gz

**Comment by TingPing** [comment]
That API was added in 3.22.

**Comment by hotice** [comment]
@TingPing I suspected that but the readme as well as meson.build mention GTK  >= 3.20 as a requirement

**Comment by TingPing** [comment]
Surely just a mistake, easily fixed by a `#if GTK_CHECK_VERSION(3, 22, 0)`

**Comment by vinszent** [comment]
Sorry, my mistake, I've fixed it now like @TingPing pointed out. I'll paste the patch here if you want to apply it.

```
From 963f1ef1993798bbc8334eee91af6ed33d8fd0c8 Mon Sep 17 00:00:00 2001
From: vinszent <vinszent@vinszent.com>
Date: Mon, 3 Apr 2017 17:29:38 +0200
Subject: [PATCH] Check if GTK+ >= 3.22 to use new gtk_show_uri func

Fixes #248
---
 src/gt-chat.c | 8 +++++++-
 src/utils.c   | 5 +++++
 2 files changed, 12 insertions(+), 1 deletion(-)

diff --git a/src/gt-chat.c b/src/gt-chat.c
index 8425285..d408db1 100644
--- a/src/gt-chat.c
+++ b/src/gt-chat.c
@@ -440,7 +440,13 @@ chat_view_button_press_cb(GtkWidget* widget,
         g_assert(GT_IS_WIN(win));
 
         if (!utils_str_empty(url))
-            gtk_show_uri_on_window(GTK_WINDOW(win), url, GDK_CURRENT_TIME, NULL); /* FIXME: Handle error here */
+        {
+#if GTK_CHECK_VERSION(3, 22, 0)
+            gtk_show_uri_on_window(GTK_WINDOW(win), url, GDK_CURRENT_TIME, NULL);
+#else
+            gtk_show_uri(NULL, url, GDK_CURRENT_TIME, NULL);
+#endif
+        }
     }
 
     g_slist_free(tags);
diff --git a/src/utils.c b/src/utils.c
index e5fd365..6a69b72 100644
--- a/src/utils.c
+++ b/src/utils.c
@@ -192,7 +192,12 @@ utils_mouse_clicked_link_cb(GtkWidget* widget,
     {
         GtWin* parent = GT_WIN_TOPLEVEL(widget);
 
+#if GTK_CHECK_VERSION(3, 22, 0)
         gtk_show_uri_on_window(GTK_WINDOW(parent), (gchar*) udata, GDK_CURRENT_TIME, NULL);
+#else
+        gtk_show_uri(NULL, (gchar*) udata, GDK_CURRENT_TIME, NULL);
+#endif
+
     }
 
     return FALSE;
-- 
2.12.1
```

**Comment by hotice** [comment]
Thank you!
